name = "downstream-lean4"
defaultTargets = [
  "aesop",
  "batteries",
  # "cslib",
  "import-graph",
  "lean4-cli",
  "LeanSearchClient",
  # "mathlib",
  "plausible",
  "ProofWidgets4",
  "quote4"
]

[[require]]
name = "aesop"
git = "https://github.com/leanprover-community/aesop"
rev = "master"

[[require]]
name = "batteries"
git = "https://github.com/leanprover-community/batteries"
rev = "main"

# [[require]]
# name = "cslib"
# git = "https://github.com/leanprover/cslib"
# rev = "main"

[[require]]
name = "import-graph"
git = "https://github.com/leanprover-community/import-graph"
rev = "main"

[[require]]
name = "lean4-cli"
git = "https://github.com/leanprover/lean4-cli"
rev = "main"

[[require]]
name = "LeanSearchClient"
git = "https://github.com/leanprover-community/LeanSearchClient"
rev = "main"

# [[require]]
# name = "mathlib4"
# git = "https://github.com/leanprover-community/mathlib4"
# rev = "master"

[[require]]
name = "plausible"
git = "https://github.com/leanprover-community/plausible"
rev = "main"

[[require]]
name = "ProofWidgets4"
git = "https://github.com/leanprover-community/ProofWidgets4"
rev = "main"

[[require]]
name = "quote4"
git = "https://github.com/leanprover-community/quote4"
rev = "master"
