name: Regular update

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  actions: write
  contents: write

concurrency:
  group: update-downstream
  cancel-in-progress: false

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.DOWNSTREAM_UPDATE_TOKEN }}
          fetch-depth: 0 # For git subtree

      - uses: astral-sh/setup-uv@v8.1.0

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update downstream
        run: |
          git subtree pull -P .downstream https://github.com/leanprover/downstream master -m "chore: update downstream"

      - name: Update subrepos
        run: |
          uv --project .downstream run .downstream/update.py . -pU

      - name: Update workflows
        run: |
          cp .downstream/workflows/update.yml .github/workflows/update.yml
          uv --project .downstream run .downstream/update_workflow_build.py . build.yml
          git add .github/workflows
          git commit -m "chore: update workflows" || echo "Workflows did not change"

      - name: Push
        run: |
          git push origin HEAD:${{ github.ref_name }}
