/-
Copyright (c) 2026 Fabrizio Montesi. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fabrizio Montesi
-/

module

public import Cslib.Foundations.Relation.Preserves
public import Cslib.Logics.Modal.Denotation

/-! # Modal Logic for Lean

This module develops the interplay between modal logic and Lean's propositional language, in order
to enable the use of modal logic to reason about standard Lean relations using `Prop`.
-/

@[expose] public section

namespace Cslib.Logic.Modal

namespace Model

/-- Given a frame `f` on `α`, constructs the modal model whose worlds are elements of `α`
and whose atoms are Lean predicates on `α` (`α → Prop`).

Valuation checks that a world satisfies a predicate. For example, under `Model.ofPredicates r`, `□P`
at `a : α` means that `P a'` holds at every `a'` such that `r a a'`. -/
abbrev ofPredicates (f : Frame α τ) : Model α τ (α → Prop) where
  toFrame := f
  v w P := P w

/-- Given a frame `f` on `α` and a container type `β` for `α` (`Membership α β`), constructs the
modal model whose worlds are elements of `α` and whose atoms are of type `β`.

Valuation is membership. For example, under `Model.ofContainers r`, `□b` at `a : α` means that
`a' ∈ b` holds for every `a'` such that `r a a'`. -/
abbrev ofContainers [Membership α β] (f : Frame α τ) : Model α τ β where
  toFrame := f
  v w p := w ∈ p

/-- Abbreviation for `Model.ofContainers` where the container type is a `Set`. -/
abbrev ofSets (f : Frame α τ) : Model α τ (Set α) := ofContainers f

/-- The set model and predicate model of a frame are definitionally equal. -/
theorem ofSets_eq_ofPredicates (f : Frame α τ) : ofSets f = ofPredicates f := rfl

end Model

open Model Relation
open scoped InferenceSystem Satisfies

/-- Under `Model.ofPredicates r`, an atomic proposition `P` holds at `a` iff `P a`. -/
@[scoped grind =, modal =]
theorem Satisfies.ofPredicates_atom_iff {P : α → Prop} (f : Frame α τ) :
    ⇓Modal[ofPredicates f,a ⊨ P] ↔ P a := Iff.rfl

/-- In the predicate model generated by `f`, `P → ∇[op]Ps` holds everywhere iff `op`
preserves the predicate map `Ps` from `P`. -/
@[scoped grind ., modal .]
theorem Satisfies.ofPredicates_preservesMap_iff {P : α → Prop} {Ps : τ.B op → α → Prop}
    (f : Frame α τ) :
    (∀ w, ⇓Modal[ofPredicates f,w ⊨ P → ∇[op](fun i => (Ps i : Proposition τ (α → Prop)))]) ↔
      f.PreservesMap op P Ps := by
  constructor
  · intro h w ws hr hP
    have h' := h w
    rw [Satisfies.imp_iff_imp] at h'
    specialize h' hP
    rw [Satisfies.nabla_iff_forall] at h'
    obtain ⟨i, hi⟩ := h' ws hr
    exact ⟨i, by simpa using hi⟩
  · intro h w
    rw [Satisfies.imp_iff_imp, Satisfies.nabla_iff_forall]
    intro hP ws hr
    obtain ⟨i, hi⟩ := h w ws hr hP
    exact ⟨i, by simpa using hi⟩

@[scoped grind =, modal =]
theorem Satisfies.ofContainers_atom_iff [Membership α β] {f : Frame α τ} {b : β} :
    ⇓Modal[Model.ofContainers f,w ⊨ (b : Proposition τ β)] ↔ w ∈ b :=
  Iff.rfl

/-- Logical equivalence under `Model.ofPredicates`. -/
abbrev Proposition.Equiv.OfPredicates (f : Frame α τ) :=
  Proposition.Equiv (Model.ofPredicates f)

/-- Logical equivalence under `Model.ofContainers`. -/
abbrev Proposition.Equiv.OfContainers [Membership α β] (f : Frame α τ) :=
  Proposition.Equiv (Model.ofContainers (β := β) f)

/-- Logically equivalent propositions under `Equiv.OfPredicates f` have the same denotation in the
Lean modal model induced by `ofPredicates f`. -/
@[scoped grind =]
theorem Proposition.equivOfPredicates_denotation_eq {f : Frame α τ}
    {φ₁ φ₂ : Proposition τ (α → Prop)} :
    (φ₁ ≡[Equiv.OfPredicates f] φ₂) ↔
      φ₁.denotation (ofPredicates f) = φ₂.denotation (ofPredicates f) :=
  equiv_iff_denotation_eq

/-- Logically equivalent propositions under `Equiv.OfContainers f` have the same denotation in the
modal model induced by `Model.ofContainers f`. -/
@[scoped grind ⇒]
theorem Proposition.equivOfContainers_denotation_eq
    [Membership α β] {f : Frame α τ} {φ₁ φ₂ : Proposition τ β} :
    (φ₁ ≡[Equiv.OfContainers (β := β) f] φ₂) ↔
      φ₁.denotation (ofContainers f) = φ₂.denotation (ofContainers f) :=
  equiv_iff_denotation_eq

/-- Pointwise conjunction of Lean predicates is logically equivalent to their modal conjunction in
the predicate model induced by `f`. -/
@[scoped grind ., modal .]
theorem Proposition.equivOfPredicates_and
    {f : Frame α τ} {P Q : α → Prop} :
    (fun a => P a ∧ Q a) ≡[Equiv.OfPredicates f] (P ∧ Q) := by
  grind

/-- Under `Equiv.OfContainers f`, if membership in the infimum of two containers is equivalent to
membership in both containers, then atomic infimum is logically equivalent to modal conjunction. -/
@[scoped grind ., modal .]
theorem Proposition.ofContainers_inf_equiv
    [Membership α β] [Min β] (f : Frame α τ) (p q : β)
    (h : ∀ x, x ∈ p ⊓ q ↔ x ∈ p ∧ x ∈ q) :
    (↑(p ⊓ q) : Proposition τ β) ≡[Equiv.OfContainers f] (p ∧ q) := by
  grind

end Cslib.Logic.Modal
