name: Build subrepos

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: [self-hosted, chonk]
    env:
      LAKE_ARTIFACT_CACHE: 1
      LAKE_RESTORE_ARTIFACTS: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install elan
        run: |
          curl https://elan.lean-lang.org/elan-init.sh -sSf | sh -s -- -y --default-toolchain none
          echo "$HOME/.elan/bin" >> "$GITHUB_PATH"

      - name: Build
        run: |
          python3 .downstream/build.py . -tl --report "$GITHUB_STEP_SUMMARY"
