name: Build subrepos

on:
  push:
    branches:
      - "**"
      - "!green"
      - "!green-nightly-*"

jobs:
  main:
    runs-on: [self-hosted, chonk]
    env:
      LAKE_ARTIFACT_CACHE: 1
      LAKE_RESTORE_ARTIFACTS: 1
      LAKE_CONFIG: ${{ github.workspace }}/.meta/lake-config.toml
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 50

      - name: Install elan
        run: |
          curl https://elan.lean-lang.org/elan-init.sh -sSf | sh -s -- -y --default-toolchain none
          echo "$HOME/.elan/bin" >> "$GITHUB_PATH"

      - name: Set cache directory
        run: echo "LAKE_CACHE_DIR=$RUNNER_TEMP/cache" >> "$GITHUB_ENV"

      - name: Restore cache
        run: |
          python3 .downstream/list.py . | while IFS= read -r repo; do
            echo "::group::cache get $repo"
            ( cd "$repo" && lake cache get --scope "$repo" ) || true
            echo "::endgroup::"
          done

      - name: Build
        run: |
          python3 .downstream/build.py . -tl \
            --report "$RUNNER_TEMP/report.md" \
            --mappings "$RUNNER_TEMP/mappings" \
            --gh-repo "${{ github.repository }}" \
            --gh-run-id "${{ github.run_id }}" \
            --gh-run-attempt "${{ github.run_attempt }}"

      - name: Add report to job summary
        if: ${{ !cancelled() }} # Even if build fails
        run: cat "$RUNNER_TEMP/report.md" >> "$GITHUB_STEP_SUMMARY"

      - name: Upload build report
        if: ${{ !cancelled() }} # Even if build fails
        uses: actions/upload-artifact@v7
        with:
          name: build-report
          path: ${{ runner.temp }}/report.md

      - name: Upload build mappings
        if: ${{ !cancelled() }} # Even if build fails
        uses: actions/upload-artifact@v7
        with:
          name: build-mappings
          path: ${{ runner.temp }}/mappings/

      - name: Upload build cache
        if: ${{ !cancelled() }} # Even if build fails
        uses: actions/upload-artifact@v7
        with:
          name: build-cache
          path: ${{ runner.temp }}/cache/
