name: Post-build on master

on:
  workflow_run:
    workflows: [Build subrepos]
    types: [completed]
    branches: [master]

concurrency:
  group: build-post
  cancel-in-progress: false

jobs:
  main:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-slim
    environment: master
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Determine nightly name
        id: nightly
        run: |
          if NIGHTLY="$(grep -P '(?<=leanprover/lean4:)nightly-.*' lean-toolchain -o)"; then
            echo "::notice::Found nightly $NIGHTLY in lean-toolchain"
            echo "nightly=$NIGHTLY" >> "$GITHUB_OUTPUT"
          else
            echo "::error::Failed to derive nightly from lean-toolchain"
            exit 1
          fi

      - name: Update nightly branch
        env:
          GH_TOKEN: ${{ secrets.PUSH_TOKEN }}
          NIGHTLY: ${{ steps.nightly.outputs.nightly }}
        run: |
          # Create the branch if it doesn't exist already.
          if gh api "repos/$GITHUB_REPOSITORY/git/refs" -X POST -f ref="refs/heads/$NIGHTLY" -f sha="$GITHUB_SHA" --silent; then
            echo "::notice::Created branch $NIGHTLY at $GITHUB_SHA"
            exit 0
          fi

          # Update the branch, but only if it can be fast-forwarded.
          # Otherwise, we may accidentally move it backwards again.
          if gh api "repos/$GITHUB_REPOSITORY/git/refs/heads/$NIGHTLY" -X PATCH -f sha="$GITHUB_SHA" --silent; then
            echo "::notice::Updated branch $NIGHTLY to $GITHUB_SHA"
            exit 0
          fi

          echo "::warning::Did not update branch $NIGHTLY to $GITHUB_SHA"

      - name: Determine lean4 nightly sha
        id: lean4-nightly
        env:
          GH_TOKEN: ${{ github.token }}
          NIGHTLY: ${{ steps.nightly.outputs.nightly }}
        run: |
          if SHA="$(gh api "repos/leanprover/lean4-nightly/git/ref/tags/$NIGHTLY" -q '.object.sha')"; then
            echo "::notice::Resolved lean4 $NIGHTLY to $SHA"
            echo "sha=$SHA" >> "$GITHUB_OUTPUT"
          else
            echo "::error::Failed to resolve lean4 $NIGHTLY to a commit"
            exit 1
          fi

      - name: Update lean4 downstream branch
        env:
          GH_TOKEN: ${{ secrets.PUSH_LEAN4_TOKEN }}
          REPO: leanprover/lean4
          BRANCH: downstream
          SHA: ${{ steps.lean4-nightly.outputs.sha }}
        run: |
          # Create the branch if it doesn't exist already.
          if gh api "repos/$REPO/git/refs" -X POST -f ref="refs/heads/$BRANCH" -f sha="$SHA" --silent; then
            echo "::notice::Created branch $BRANCH in $REPO at $SHA"
            exit 0
          fi

          # Update the branch, but only if it can be fast-forwarded.
          # Otherwise, we may accidentally move it backwards again.
          if gh api "repos/$REPO/git/refs/heads/$BRANCH" -X PATCH -f sha="$SHA" --silent; then
            echo "::notice::Updated branch $BRANCH in $REPO to $SHA"
            exit 0
          fi

          echo "::warning::Did not update branch $BRANCH in $REPO to $SHA"
