name: On PR push

on:
  pull_request_target:
    types: [synchronize]

jobs:
  remove-cache-available-label:
    runs-on: ubuntu-slim
    permissions:
      pull-requests: write
    steps:
      - name: Remove cache-available label
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr edit "${{ github.event.pull_request.number }}" \
            --repo "${{ github.repository }}" --remove-label cache-available
